# Food Delivery Data Exploration and Analysis 3

# Agenda of the lecture

* Matrix multiplication Recap
  * Np.dot
  * Np.matmul
  * `@`
* Vectorization
* Broadcasting
* Np.tile
* Split
    * np.hsplit
    * np.vsplit
* Stacking

# Matrix multiplication Recap

## <span style="color: skyblue;"> Element-wise Multiplication </span>

Element-wise multiplication multiplies corresponding elements in two arrays.
This uses the <font color="red">*</font> operator in NumPy.

We’ll perform element-wise multiplication on numeric columns like:
- `votes` and `rate`: To calculate a **weighted vote score**.



In [ ]:
import numpy as np

ratings = np.array([4.9, 4.1, 4.8])
votes = np.array([ 775,  787,  918])
weighted_scores = votes * ratings

print("Weighted scores (sample):\n", weighted_scores)

Weighted scores (sample):
 [3797.5 3226.7 4406.4]


**Explanation:**
- Element-wise multiplication combines ratings and votes to create a weighted metric.
- This can be used for scoring restaurants based on popularity and quality.

In [ ]:
vote_by_5 = votes * 5

print(vote_by_5[:5])

[3875 3935 4590]


In [ ]:
# This is an array multiplied by an array of a different shape
# This is expected to fail!

vote_by_array = votes * np.array([1,2,3,4])

print(vote_by_array)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

**Takeaway:**
* Array * Number  →  WORKS
* Array * Array (same shape)  →  WORKS
* Array * Array (different shape)  →  DOES NOT WORK

## <span style="color: skyblue;"> Matrix Multiplication </span>

We’ll calculate a transformation using:
* Ratings, Votes, and Approximate Costs.
* Methods:
    * np.dot()
    * np.matmul()
    * @ operator.


In [ ]:
# numeric_data
numeric_data = np.arange(11,20).reshape(3,3)

# Create a random transformation matrix
transformation_matrix = np.array([[1.2, 0.8, 0.5],
                                   [0.5, 1.5, 1.0],
                                   [0.7, 0.6, 1.8]])

# Matrix multiplication using np.dot()
transformed_data_dot = np.dot(numeric_data, transformation_matrix)

# Matrix multiplication using @ operator
transformed_data_at = numeric_data @ transformation_matrix

# Matrix multiplication using np.matmul()
transformed_data_matmul = np.matmul(numeric_data, transformation_matrix)

print("Transformed Data (np.dot):\n", transformed_data_dot)
print("---"* 10)
print("Transformed Data (@ operator):\n", transformed_data_at)
print("---"* 10)
print("Transformed Data (np.matmul):\n", transformed_data_matmul)
print("---"* 10)


Transformed Data (np.dot):
 [[28.3 34.6 40.9]
 [35.5 43.3 50.8]
 [42.7 52.  60.7]]
------------------------------
Transformed Data (@ operator):
 [[28.3 34.6 40.9]
 [35.5 43.3 50.8]
 [42.7 52.  60.7]]
------------------------------
Transformed Data (np.matmul):
 [[28.3 34.6 40.9]
 [35.5 43.3 50.8]
 [42.7 52.  60.7]]
------------------------------


**Explanation:**
- A transformation matrix allows us to apply scaling and weighting to the original data.
- np.dot(), @, and np.matmul() produce the same results for matrix multiplication.



**Rule:** The Number of columns of the first matrix should be equal to the number of rows of the second matrix.

- (A, B) * (B, C) -> (A, C)
- (3,4) * (4,3) -> (3,3)

<span style="background-color: Blue;">[Visual Demo:](https://www.geogebra.org/m/ETHXK756)</span>

In [ ]:
# This is expected to fail!
a = np.array([1,2,3,4])
a@5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
# This is expected to fail!
np.matmul(a, 5)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.dot(a, 5)

array([ 5, 10, 15, 20])

<span style="color: red;"> **Important:** </span>

- `dot()` function supports the vector multiplication with a scalar value, which is not possible with `matmul()`.
- `Vector * Vector` will work for `matmul()` but `Vector * Scalar` won't.

### Business Context

Matrix operations in Zomato analytics allow efficient computation of weighted scores and composite metrics by combining votes, ratings, and costs. This helps businesses evaluate restaurant popularity and quality, create recommendation systems, prioritize listings, and make data-driven decisions for promotions and strategic initiatives.

# Broadcasting

## <span style="color: violet;"> What is Broadcasting? </span>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/169/326/original/download.jpeg?1764923433" width="500" />

Broadcasting allows NumPy to perform operations on arrays with different shapes by automatically "expanding" smaller arrays.

It simplifies computation by avoiding the need for explicit loops or manual reshaping.

**Example:** Adding a scalar to a 2D array works because NumPy "broadcasts" the scalar to match the array's shape.


In [ ]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

result = array_2d + scalar
print("Array:\n", array_2d)
print("---"* 10)

print("adding Scalar:", scalar)
print("---"* 10)

print("Result after broadcasting:\n", result)

Array:
 [[1 2 3]
 [4 5 6]]
------------------------------
adding Scalar: 10
------------------------------
Result after broadcasting:
 [[11 12 13]
 [14 15 16]]


**Explanation:**
* The scalar 10 is broadcast to match the shape of `array_2d`.
* NumPy performs the operation as if the scalar is a 2D array with the same shape.

## <span style="color: skyblue;"> Broadcasting in 1D Arrays </span>
### Case 1: Dimensions of Both Arrays Are Equal

If two arrays have the same shape, operations work without any issues.

In [ ]:
# Arrays with the same shape
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition
result = array1 + array2
print(f"{array1} + {array2} = {result}")

[1 2 3] + [4 5 6] = [5 7 9]


### Case 2: One Array is 1D

If one array is 1D and the other is higher-dimensional, broadcasting will expand the 1D array.


In [ ]:
# Broadcasting a 1D array to a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Broadcasting works
result = array_2d + array_1d

print(f"{array_2d} + {array_1d} =")
print("---"* 10)
print(result)

[[1 2 3]
 [4 5 6]] + [10 20 30] =
------------------------------
[[11 22 33]
 [14 25 36]]


**Explanation:**
* The 1D array [10, 20, 30] is broadcast to match the rows of the 2D array.

### Case 3: Column and Row Matrices

Broadcasting works between a column matrix and a row matrix.

In [ ]:
# Column matrix (3x1) and row matrix (1x3)
col_matrix = np.array([[1], [2], [3]])
row_matrix = np.array([[10, 20, 30]])

# Broadcasting works
result = col_matrix + row_matrix

print(f"{col_matrix} + {row_matrix} =")
print("---"* 10)
print(result)

[[1]
 [2]
 [3]] + [[10 20 30]] =
------------------------------
[[11 21 31]
 [12 22 32]
 [13 23 33]]



**Explanation:**
* The column matrix is broadcast along the columns, and the row matrix is broadcast along the rows.


## <span style="color: skyblue;"> Error: Some Incompatible Shapes </span>
Broadcasting fails when the shapes are incompatible. Let’s see an example.

In [ ]:
# Incompatible shapes
# This is expected to fail!
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2], [3, 4]])

result = array1 + array2
result

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

**Explanation:**
* The shapes (3,) and (2, 2) are incompatible for broadcasting.


## <span style="color: skyblue;"> Broadcasting in 2D Arrays </span>



**Four Rules for Broadcasting in 2D Arrays**

1. If the arrays do not have the same number of dimensions, prepend 1s to the smaller array.
2. Arrays are compatible if:
   - Dimensions are the same, or
   - One of the dimensions is 1.
3. The result shape is the maximum shape along each dimension.
4. If rules are not satisfied, broadcasting fails.

Let’s explore examples of what works and what doesn’t.


In [ ]:
# Example: Compatible shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

# Broadcasting works
result = array1 + array2

print("Array 1:\n", array1)
print("---"* 10)

print("Array 2:\n", array2)
print("---"* 10)

print("Result:\n", result)

Array 1:
 [[1 2 3]
 [4 5 6]]
------------------------------
Array 2:
 [[10]
 [20]]
------------------------------
Result:
 [[11 12 13]
 [24 25 26]]


**Explanation:**
* Shape of array1 is (2, 3) and array2 is (2, 1).
* Broadcasting expands array2 to (2, 3).

In [ ]:
# Example: Incompatible shapes
# This is expected to fail!
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20]])

result = array1 + array2
result

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

**Explanation:**
- Shape of `array1` is `(2, 3)` and `array2` is `(1, 2)`.
- Broadcasting fails because the dimensions are not compatible.

### Business Context

In Zomato restaurant analytics, we often need to perform operations across datasets or attributes with different shapes. For example:

- Adding a fixed promotional discount to all restaurant costs.
- Adjusting votes or ratings with scaling factors for normalization.
- Combining column-wise and row-wise metrics (e.g., votes per cuisine type vs. per city).
- Broadcasting in NumPy allows these operations to happen automatically and efficiently, without manually reshaping arrays or writing explicit loops. This enables fast computations on large datasets and simplifies transformations for scoring, normalization, or customized metrics.
- Using broadcasting ensures that businesses can scale analytics across thousands of restaurants, apply promotions, or compute composite metrics consistently and efficiently, saving time and avoiding errors.


## <span style="color: skyblue;"> Using np.tile() </span>

When broadcasting doesn’t work, you can explicitly expand an array using np.tile().



In [ ]:
# Example: Explicit broadcasting with np.tile
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20], [30]])

# Use np.tile to match shapes
array1_tiled = np.tile(array1, (3, 1))
array1_tiled

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# Perform addition
result = array1_tiled + array2
print("Result:\n", result)

Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


### Business Context
In Zomato analytics, np.tile() helps align arrays with different shapes, ensuring consistent calculations across restaurant attributes. This enables reliable scoring, normalization, and custom metric computations, supporting accurate promotions, rating adjustments, and data-driven decisions at scale.

**Explanation:**
* np.tile() repeats array1 to match the shape of array2.
* Broadcasting is now possible.

---


# Question
What happens here?
```
import numpy as np
A = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(A + b)
```
# Choices
- [x] `[[11, 21, 31], [12, 22, 32], [13, 23, 33]]`
- [ ] `[[11], [22], [33]]`
- [ ] Error (shapes mismatch)
- [ ] `[11, 22, 33]`

# Vectorization

## <span style="color: skyblue;"> Why Vectorization is Necessary </span>

### The Problem with Non-Vectorized Operations

When working with arrays, applying a Python function directly to a NumPy array often leads to errors.

Let’s see an example where we try to use a Python function on a column of the dataset.



In [ ]:
# Example: Apply a custom function to the 'rate' column
def categorize_rating(rating):
    "Categorize ratings into high or low."""
    if rating >= 4.0:
        return "High"
    else:
        return "Low"

In [ ]:
# Attempt to apply the function directly
# This is expected to fail!
categorized_ratings = categorize_rating(numeric_data[:, 0])  # 'rate' column
categorized_ratings

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Explanation:**
* Python functions like categorize_rating are not designed to work directly on NumPy arrays.
* NumPy operates on arrays element-wise, but Python functions expect single values.
* This results in a ValueError or other unexpected behavior.

## <span style="color: skyblue;"> Introducing np.vectorize() </span>

Np.vectorize() allows us to apply Python functions element-wise to a NumPy array.

Let’s vectorize the categorize_rating() function and apply it to the rate column.

## <span style="color: violet;"> How can we categorize restaurants as "High" or "Low" rated based on their customer ratings to segment and prioritize them for analysis or marketing? </span>


In [ ]:
# Vectorize the categorize_rating function
vectorized_categorize_rating = np.vectorize(categorize_rating)
vectorized_categorize_rating

In [ ]:
# Apply the vectorized function to the 'rate' column
categorized_ratings = vectorized_categorize_rating(numeric_data[:, 0])

# Display a sample of the categorized ratings
print("Categorized Ratings (sample):", categorized_ratings[:10])

Categorized Ratings (sample): ['High' 'High' 'High']


**Explanation:**
* np.vectorize() transforms a Python function into one that works seamlessly with arrays.
* This enables element-wise operations without needing loops.


## <span style="color: skyblue;"> Applying Discounts to Costs </span>
## <span style="color: violet;"> How can we apply a 10% discount to restaurants with ratings of 4.0 or higher to incentivize high-quality options and calculate their new costs? </span>


In [ ]:
# Define a function to calculate the discounted cost
def discount_cost(rate, cost):
    "Apply a 10% discount if the rating is 4.0 or higher."""
    if rate >= 4.0:
        return cost * 0.9
    else:
        return cost

# Vectorize the discount_cost function
vectorized_discount_cost = np.vectorize(discount_cost)

# Apply the vectorized function to 'rate' and 'approx_cost(for two people).'
discounted_costs = vectorized_discount_cost(numeric_data[:, 0], numeric_data[:, 2])

# Display a sample of the discounted costs
print("Discounted Costs (sample):", discounted_costs[:10])


Discounted Costs (sample): [11.7 14.4 17.1]


**Explanation:**
* The function `discount_cost()` checks each restaurant's rating and applies a discount if it meets the criteria.
* `np.vectorize()` enables this logic to process the entire dataset column efficiently.

### Business Context

Vectorization in Zomato analytics enables fast, scalable application of business rules—like rating-based categorization, dynamic pricing, and targeted promotions—across entire datasets. This allows businesses to efficiently segment restaurants and make data-driven decisions without slow, explicit loops.



# Split

## <span style="color: skyblue;"> Parameters for Splitting Arrays </span>

All splitting functions take the following parameters:

1. array: The array to be split.
2. indices_or_sections:
   - If an integer `N`, the array is split into `N` equal sections.
   - If a list of indices, the splits happen at those positions.

## <span style="color: skyblue;"> Splitting Arrays with np.split() </span>

`np.split()` splits an array into sections along a specified axis:
- **axis=0**: Split rows.
- **axis=1**: Split columns (for 2D arrays).


**Example 1: Splitting a 1D Array**


In [ ]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 sections
split_1d = np.split(array_1d, 3)

print("Original Array:", array_1d)
print("Splits:", split_1d)

Original Array: [1 2 3 4 5 6]
Splits: [array([1, 2]), array([3, 4]), array([5, 6])]


**Prerequisites for Splitting**

- The total number of elements **must be divisible** by the number of splits.
- For 2D arrays, ensure the axis matches the shape of the array.

**Example**:
- A 1D array with 6 elements can be split into 2 or 3 equal parts, but **not 4**.
- A 2D array with 4 columns can be split horizontally into 2 parts, but **not 3**.


In [ ]:
# This is expected to fail!
split_1d = np.split(array_1d, 4)

ValueError: array split does not result in an equal division

**Example 2: Splitting a 2D Array**

In [ ]:
# 2D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

# Split into 2 along axis=1 (columns)
split_2d = np.split(array_2d, 2, axis=1)

print("Original Array:\n", array_2d)
print("=="*10)
print("Splits:")
for part in split_2d:
    print(part)


Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Splits:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


**Explanation:**
- **1D Array**: Split into 3 equal parts.
- **2D Array**: Split columns into 2 equal sections using `axis=1`.


### Business Context

In Zomato analytics, np.split() allows efficient partitioning of datasets by restaurants, cuisines, or metrics. This supports training predictive models, segment-level analysis, and parallel processing, enabling faster, consistent, and actionable business insights.

## <span style="color: skyblue;"> Horizontal Splitting with np.hsplit() </span>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/169/330/original/hvsp1.png?1764924592" width="500" />

`np.hsplit()` splits a 2D array horizontally into sections (columns).

>**Shortcut:** Equivalent to np.split(array, N, axis=1).

**Example: Horizontal Splitting**



In [ ]:
# Horizontal split
hsplit_2d = np.hsplit(array_2d, 2)

print("Original Array:\n", array_2d)
print("=="*10)
print("Horizontal Splits:")
for part in hsplit_2d:
    print(part)


Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Horizontal Splits:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


**Explanation:**
- `np.hsplit()`  divides the columns into equal sections.
- This is a convenient method for column-wise splitting.


## <span style="color: skyblue;"> Vertical Splitting with np.vsplit() </span>

`np.vsplit()` splits a 2D array vertically into sections (rows).

>**Shortcut:** Equivalent to np.split(array, N, axis=0).

**Example: Vertical Splitting**



In [ ]:
# Vertical split
vsplit_2d = np.vsplit(array_2d, 2)

print("Original Array:\n", array_2d)
print("Vertical Splits:")
for part in vsplit_2d:
    print(part)


Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Vertical Splits:
[[1 2 3 4]]
[[5 6 7 8]]


**Explanation:**
* `np.vsplit()` divides rows into equal sections.
* This is a convenient method for row-wise splitting.

## <span style="color: skyblue;"> Custom Splits with Indices </span>

Instead of dividing into equal parts, we can use indices for custom splits.


In [ ]:
# Split using indices
custom_split = np.split(array_1d, [2, 5])

print("Original Array:", array_1d)
print("Custom Splits:", custom_split)


Original Array: [1 2 3 4 5 6]
Custom Splits: [array([1, 2]), array([3, 4, 5]), array([6])]


**Explanation:**
- Splits occur at positions `[2, 5]`, creating 3 parts:
  - `[1, 2]`
  - `[3, 4, 5]`
  - `[6]`.

### Business Context

In Zomato analytics, horizontal, vertical, and custom array splits enable targeted analysis of features and restaurant segments. This supports efficient processing of large datasets, driving precise insights for pricing strategies, promotions, and feature-level decision-making.



# Question
What will be the output?
```
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(np.hsplit(arr, 2))
```
# Choices
- [x] `[array([[1], [3], [5]]), array([[2], [4], [6]])]`
- [ ] `[array([[1, 2]]), array([[3, 4], [5, 6]])]`
- [ ] `[array([1, 3, 5]), array([2, 4, 6])]`
- [ ] Error

# Stacking

## <span style="color: skyblue;"> Vertical Stacking with np.vstack() </span>

`np.vstack()` stacks arrays along the vertical axis (rows).
* All arrays must have the same number of columns for vertical stacking.

**Example: Vertical Stacking**



In [ ]:
import numpy as np

# Define arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack vertically
vstack_result = np.vstack([array1, array2])

print("Array 1:", array1)
print("Array 2:", array2)
print("Vertical Stack:\n", vstack_result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


**Explanation:**
- The arrays `[1, 2, 3]` and `[4, 5, 6]` are stacked row-wise to form a 2D array.

`np.vstack()` requires arrays to have the same number of columns.

Let’s see what happens when this condition is not met.


In [ ]:
# Arrays with unequal sizes
# This is expected to fail!
array3 = np.array([7, 8])

vstack_error = np.vstack([array1, array3])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

**Explanation:**
- Vertical stacking fails because `array3` has fewer elements than `array1`.
- All arrays must have the same number of columns for `np.vstack()`.


## <span style="color: skyblue;"> Horizontal Stacking with np.hstack() </span>

`np.hstack()` stacks arrays along the horizontal axis (columns).
* All arrays must have the same number of rows for horizontal stacking.

**Example: Horizontal Stacking**



In [ ]:
# Define arrays
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

# Stack horizontally
hstack_result = np.hstack([array4, array5])

print("Array 4:\n", array4)
print("Array 5:\n", array5)
print("Horizontal Stack:\n", hstack_result)

Array 4:
 [[1]
 [2]
 [3]]
Array 5:
 [[4]
 [5]
 [6]]
Horizontal Stack:
 [[1 4]
 [2 5]
 [3 6]]


**Explanation:**
- Arrays `array4` and `array5` are stacked column-wise to form a 2D array.

`np.hstack()` requires arrays to have the same number of rows.

Let’s see what happens when this condition is not met.



In [ ]:
# Arrays with unequal rows
# This is expected to fail!
array6 = np.array([[7], [8]])

hstack_error = np.hstack([array4, array6])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

**Explanation:**
- Horizontal stacking fails because `array6` has fewer rows than `array4`.
- All arrays must have the same number of rows for `np.hstack()`.

### Business Context

In Zomato analytics, we often work with multiple datasets or features that need to be combined for comprehensive analysis. Stacking arrays allows us to merge data along rows or columns efficiently:

- Vertical stacking (np.vstack): Combine multiple datasets of the same features (columns) but different restaurants (rows). Example: Adding new restaurant entries to an existing dataset.
- Horizontal stacking (np.hstack): Merge different features (columns) for the same set of restaurants (rows). Example: Combining votes, ratings, and approximate costs into a single 2D array for analysis.
- Ensures data alignment and consistency, which is crucial for downstream tasks like scoring, filtering, or visualization.
- Helps maintain structured, tabular data while performing feature engineering, aggregations, or building predictive models.


## <span style="color: skyblue;"> General Concatenation with np.concatenate() </span>

`np.concatenate()` concatenates arrays along any axis (default is `axis=0`).  
It provides more flexibility than stacking functions.

**Parameters:**
1. **array:** List or tuple of arrays to concatenate.
2. **axis:** Axis along which to concatenate.
   - `axis=0`: Concatenate rows.
   - `axis=1`: Concatenate columns (for 2D arrays).


In [ ]:
# Example 1: Concatenation Along Rows
# Concatenate along axis=0 (rows)
concat_rows = np.concatenate([array4, array5], axis=0)

print("Concatenation Along Rows:\n", concat_rows)

Concatenation Along Rows:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


**Explanation:**
- Arrays `array4` and `array5` are concatenated row-wise into a single array.

In [ ]:
# Example 2: Concatenation Along Columns
# Concatenate along axis=1 (columns)
concat_columns = np.concatenate([array4, array5], axis=1)

print("Concatenation Along Columns:\n", concat_columns)

Concatenation Along Columns:
 [[1 4]
 [2 5]
 [3 6]]


**Explanation:**
- Arrays `array4` and `array5` are concatenated column-wise into a single array.

`np.concatenate()` requires compatible dimensions along the non-concatenating axis.

Let’s see what happens when this condition is not met.

In [ ]:
# Arrays with incompatible shapes
# This is expected to fail!
array7 = np.array([7, 8, 9])

concat_error = np.concatenate([array4, array7], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Explanation:**
- Concatenation along `axis=1` fails because `array7` does not match the row count of `array4`.
- Always ensure compatible dimensions for `np.concatenate()`.

### Business Context

In restaurant analytics, np.concatenate() enables efficient integration of datasets across restaurants, features, or time periods. By combining rows or columns, it supports comprehensive analyses, feature engineering, and predictive modeling, ensuring aligned, complete datasets for accurate business insights.

# Question
What will be the output of:
```
import numpy as np
a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.concatenate((a, b), axis=1))
```
# Choices
- [x] `[[1, 2, 3, 4]]`
- [ ] `[[1, 2], [3, 4]]`
- [ ] `[[1, 3], [2, 4]]`
- [ ] Error